language: python

python:
  - "3.6"
  - "3.7-dev"

services:
    - postgresql

cache:
    pip: true

install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .

before_script:
  - cp .database.yml.travis config/database.yml

# command to run tests
script: make coverage

after_success:
  - coveralls


