version: "2"

services:

    postgres:
        build:
            context: .
            dockerfile: Dockerfile.postgres
            args:
                POSTGRES_PASSWORD: FaithSubjectToChange

        image: "dev-postgres"

        container_name: dev-PostgreSql

        environment:
            POSTGRES_PASSWORD: FaithSubjectToChange

    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev

        image: "dev-mishmash"

        container_name: dev-MishMash
        depends_on:
            - postgres

        environment:
           MISHMASH_DBURL: postgresql://mishmash:FaithSubjectToChange@postgres/MishMash

        links:
            - postgres:postgres

        volumes:
            - /etc/localtime:/etc/localtimel:ro
            - ~/var/music/:/media/new:ro
            - ~/Music/:/media/music:ro
            - /mnt/Media/Friends/Music/:/media/friends:ro

        ports:
            - "6229:6229"
