version: "3"

services:
    # MishMash images
    mishmash: &mishmash-image
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VERSION: $VERSION
        image: mishmash

    mishmash-publish:
        <<: *mishmash-image
        image: nicfit/mishmash:$VERSION

    # MishMash containers
    mishmash-local: &mishmash-container
        image: mishmash
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${MUSIC_DIR}:/media/music:ro

    mishmash-sqlite:
        <<: *mishmash-container
        image: nicfit/mishmash:$VERSION
        container_name: MishMash-sqlite
        environment:
            MISHMASH_DBURL: sqlite:////MishMash/var/MishMash.db
        ports:
            - "16229:6229"

    # Postgresql database container
    postgres:
        container_name: PostgreSql-mishmash-devel
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: mishmash-devel
            POSTGRES_USER: mishmash
            POSTGRES_PASSWORD: TheFaithSubjectToChange

    mishmash-postgres:
        <<: *mishmash-container
        image: nicfit/mishmash:$VERSION
        container_name: MishMash-postgreSQL
        environment:
            POSTGRES_PASSWORD: TheFaithSubjectToChange
            MISHMASH_DBURL: postgresql://mishmash:TheFaithSubjectToChange@postgres/MishMash
        links:
            - postgres:postgres
        ports:
            - "26229:6229"
        depends_on:
            - postgres

